# Generated by Django 4.1.4 on 2022-12-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
